config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'events#index'
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :datevent, :adress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "validate" %>
  </div>
  <div class="input-field">
    <%= f.label :datevent %><br>
    <%= f.date_select :datevent, :class => "validate" %>
  </div>
  <div class="input-field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress , :class => "materialize-textarea"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Events</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Datevent</th>
      <th>Adress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.datevent %></td>
        <td><%= event.adress %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h2>New Event</h2>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Datevent:</strong>
  <%= @event.datevent %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @event.adress %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrailslab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	 <nav>
    <div class="container">
      <a href="/" class="brand-logo">MyRailsLab</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "Contact", new_contact_path %></li>
        <li><%= link_to "Contact us", contact_us_path %></li>
        <li><a href="sass.html">Events</a></li>
      </ul>
    </div>
  </nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>